### PR TITLE
Add Django 3.1 and Python 3.9 support

### PR DESCRIPTION
**Pull request by ynerant**
Django 3.1 and Python 3.9 are released :)

### CODE REVIEW

**Comment by nitmir** [comment]
Hi Ynerant
This look nice to me. However, could you also edit the .travis.yml according to your last commit for the travis CI tests to pass ?

**Comment by ynerant** [comment]
Travis is completely broken when I force push. I'm trying to have a pretty branch, I will try some things

**Comment by ynerant** [comment]
Well, I don't understand why Travis is not running the good configuration file...
https://travis-ci.org/github/nitmir/django-cas-server/builds/756252920/config vs https://github.com/ynerant/django-cas-server/blob/master/.travis.yml

**Comment by ynerant** [comment]
I really don't understand why Travis is appearing to be broken...
I mirrored the repository on a Gitlab instance, and the gitlab-ci is running fine: https://gitlab.crans.org/ynerant/django-cas-server/-/pipelines/5657
I also activated Travis on my Github fork. This time the number of jobs is coherent, but surprisingly Python 2 is not working, while it is working on Gitlab: https://travis-ci.com/github/ynerant/django-cas-server/builds/217481580

I really think that Travis is broken, but not django-cas-server.

**Pull request merged**
